### ISSUE TITLE
Add support for observing network calls in debug interface

### ISSUE THREAD

**Issue by dmacra** [npr/RAD-iOS#7]
**Is your feature request related to a problem? Please describe.**
We need support to observe requests that are executed by RAD framework enabling testability of RAD framework integration into client application.

**Describe the solution you'd like**
Provide a protocol with a function that reports all performed ```URLRequest``` objects

**Describe alternatives you've considered**
N/A

**Additional Context**
N/A

**Comment by david-livadaru-3pillarglobal** [comment]
Available from version `1.1.0`.
